= JRuby Gradle

link:https://github.com/jruby-gradle[JRuby Gradle] is a set of
link:http://gradle.org[Gradle] plugins which make it easy to build, test,
manage and package link:http://jruby.org[JRuby] projects.  By relying on Gradle
to provide much of the basic task and dependency management functionality,
JRuby Gradle provides high quality build tooling for Ruby and Java developers.


== Quick Start

The most basic use-case might be running some
link:http://rspec.info[RSpec]-based tests with JRuby Gradle's
link:http://plugins.gradle.org/plugin/com.github.jruby-gradle.base[base
plugin].

[source,gradle]
.build.gradle
----
include::examples/rspec.gradle[]
----

Using the `build.gradle` above, running `./gradlew spec` will result in the
Ruby-based dependencies being resolved and installed, then `JRubyExec` will
execute RSpec using JRuby.

NOTE: The version in the above example might be out of date, please refer to the
link:http://plugins.gradle.org/plugin/com.github.jruby-gradle.base[release
page] for the latest version of the base plugin.

More examples can be found in the link:cookbook.html[JRuby Gradle Cookbook].

== Plugins

=== Base

The base plugin is the foundation for all of the other plugins. It provides the
core JRuby dependency, Ruby gem dependency resolution and the
link:plugins/base.html#jrubyexec[JRubyExec] task type.

Learn more about link:plugins/base.html[the base plugin]

=== Jar

The jar plugin helps package `.jar` files for projects. The plugin supports creating `.jar` artifacts that are ready to be included in other projects, it also supports creating self-contained executable archives.

Learn more about link:plugins/jar.html[the jar plugin]

=== War 

Like the <<Jar>> plugin, the war plugin helps package `.war` files for
projects. Unlike the Jar plugin this plugin is primarily responsible for
creating JRuby-based web application artifacts. Similar to the <<Jar>> however,
the war plugin can create self-contained executable archives.

Learn more about link:plugins/war.html[the war plugin]

=== Storm

The Storm plugin enables developers to create
link:http://storm.apache.org[Apache Storm] applications, also referred to as
"topologies", in Ruby via the link:redstorm.html[Redstorm] library.

Learn more about link:plugins/storm.html[the storm plugin]


// vim: ft=asciidoc
